function powerClass(kw){return [25,50,120].includes(Number(kw))?'power-'+Number(kw):'power-other'}
const $=s=>document.querySelector(s),fmt=n=>Number(n).toLocaleString('th-TH');const esc=s=>String(s??'ไม่ระบุ').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let chargers=[],view='all',zoom=7,selected=null;
let sites=[...new Set(chargers.map(d=>d.site))].map(id=>({id,devices:chargers.filter(d=>d.site===id)}));
[...new Set(chargers.map(d=>d.office).filter(Boolean))].sort().forEach(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;$('#center').append(o)});
function warrantyState(d){const value=String(d.warranty||'').trim();if(/^(ยังไม่หมดประกัน|ไม่หมดประกัน|อยู่ในประกัน|อยู่ในระยะประกัน|ในประกัน)$/.test(value))return 'covered';if(value==='หมดประกัน')return 'expired';return 'unknown'}
function warrantyLabel(d){return {expired:'หมดประกัน',covered:'ยังไม่หมดประกัน',unknown:'ไม่ระบุข้อมูลการรับประกัน'}[warrantyState(d)]}
function filtered(){return chargers.filter(d=>(!$('#center').value||d.office===$('#center').value)&&(!$('#power').value||d.kw===+$('#power').value)&&(!$('#warranty').value||warrantyState(d)===$('#warranty').value))}
function visible(){return filtered().filter(d=>(view==='all'||(view==='done'?d.repairs.length:d.status==='เสีย'))&&(!$('#status').value||d.status===$('#status').value)&&(d.name+' '+d.id).toLowerCase().includes($('#search').value.toLowerCase()))}
function render(){const ds=filtered(),rs=ds.flatMap(d=>d.repairs);const cards=[['สถานีอัดประจุไฟฟ้า',new Set(ds.map(d=>d.site)).size,'แห่ง','นับตาม Station No.','⌖','var(--purple)'],['กำลังพิกัดรวม',ds.reduce((s,d)=>s+d.kw,0),'kW','ผลรวมกำลังพิกัดตามทะเบียน','ϟ','var(--amber)'],['เครื่องอัดประจุไฟฟ้า',ds.length,'เครื่อง','นับตาม Charger ID','▣','var(--purple)'],['พร้อมใช้งาน',ds.filter(d=>d.status==='ใช้งาน').length,'เครื่อง','สถานะตามทะเบียนต้นทาง','✓','var(--green)'],['ชำรุด',ds.filter(d=>d.status==='เสีย').length,'เครื่อง','สถานะตามทะเบียนต้นทาง','!','var(--amber)'],['รายการซ่อมบำรุง',rs.length,'รายการ','รายการอะไหล่และงานซ่อมบำรุง','⚒','var(--purple)'],['ค่าใช้จ่ายในการซ่อมบำรุง',rs.reduce((s,r)=>s+(r.cost||0),0),'บาท','ผลรวมค่าใช้จ่ายรายรายการ','฿','var(--purple)']];$('#stats').innerHTML=cards.map(([label,v,u,n,icon,col])=>`<article class="stat ${label==='รายการซ่อมบำรุง'?'repair-stat':''}" style="--accent:${col}"><div class="stathead">${label}<span class="icon">${icon}</span></div><div class="value">${fmt(v)}<small>${u}</small></div>${label==='รายการซ่อมบำรุง'?'<button id="repair-all" class="repair-action">แสดงประวัติการซ่อมบำรุง</button>':''}</article>`).join('');$('#repair-all').onclick=()=>openRepairs(filtered());$('#rows').innerHTML=visible().map(d=>`<tr tabindex="0" role="button" data-id="${esc(d.id)}" aria-label="แสดงรายละเอียด ${esc(d.name)}"><td data-label="สถานี / เครื่องอัดประจุ"><strong>${esc(d.name)}</strong><small>${esc(d.id)} · ${esc(d.brand)}</small></td><td data-label="หน่วยงานรับผิดชอบ">${esc(d.office)}</td><td data-label="กำลังพิกัด"><span class="power-chip ${powerClass(d.kw)}">${d.kw} kW</span></td><td data-label="วันที่ PM">${esc(d.pm||'ไม่ระบุวันที่ PM')}</td><td data-label="การรับประกัน"><span class="warranty-badge ${warrantyState(d)}">${warrantyLabel(d)}</span></td><td data-label="สถานะการใช้งาน"><span class="badge ${d.status==='เสีย'?'missing':''}">${esc(d.status==='ใช้งาน'?'พร้อมใช้งาน':d.status==='เสีย'?'ชำรุด':d.status)}</span></td><td data-label="ประวัติการซ่อมบำรุง">${d.repairs.length?`<button class="repair-action" data-repair-device="${esc(d.id)}">${d.repairs.length} รายการ · แสดงรายละเอียด</button><small>${fmt(d.repairs.reduce((s,r)=>s+r.cost,0))} บาท</small>`:'<small>ไม่พบประวัติการซ่อมบำรุง</small>'}</td></tr>`).join('')||'<tr><td colspan="7">ไม่พบข้อมูลตามตัวกรอง</td></tr>';document.querySelectorAll('[data-id]').forEach(b=>{const open=()=>{selected=chargers.find(d=>d.id===b.dataset.id).site;mapChosenSite=selected;detail();focusStationMap();drawMap();revealStation()};b.onclick=open;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});const allowed=new Set(visible().map(d=>d.site));if(!allowed.has(selected))selected=[...allowed][0];detail();drawMap();document.querySelectorAll('[data-repair-device]').forEach(b=>b.onclick=e=>{e.stopPropagation();openRepairs(chargers.filter(d=>d.id===b.dataset.repairDevice))});}
function detail(){const site=sites.find(s=>s.id===selected);$('#regionCount').textContent=`${new Set(visible().map(d=>d.site)).size} แห่ง`;if(!site){$('#regions').innerHTML='<p>ไม่พบสถานีตามตัวกรอง</p>';return}const ds=site.devices,d=ds[0];$('#regions').innerHTML=`<div class="detail-title"><h2>${esc(d.name.replace(/ #\d+$/,''))}</h2><small>${esc(site.id)}</small><p>${ds.length} เครื่อง · กำลังรวม ${fmt(ds.reduce((s,d)=>s+d.kw,0))} kW</p><div class="station-map-links"><a href="https://www.google.com/maps?q=${d.lat},${d.lon}" target="_blank" rel="noopener">Google Maps</a><a class="street-view-link" href="https://www.google.com/maps/@?api=1&amp;map_action=pano&amp;viewpoint=${encodeURIComponent(d.lat+','+d.lon)}" target="_blank" rel="noopener" aria-label="เปิด Google Street View ของ ${esc(d.name)}">Street View</a><a href="https://www.google.com/maps/dir/?api=1&amp;destination=${encodeURIComponent(d.lat+','+d.lon)}" target="_blank" rel="noopener">นำทาง</a></div><small>Street View แสดงภาพบริเวณใกล้เคียงตามที่ Google มีข้อมูล</small></div>`+ds.map(d=>`<article class="device"><div class="regionhead"><b>${esc(d.name)}</b><span class="badge ${d.status==='เสีย'?'missing':''}">${esc(d.status==='ใช้งาน'?'พร้อมใช้งาน':d.status==='เสีย'?'ชำรุด':d.status)}</span></div><div class="devicepower"><span class="power-chip ${powerClass(d.kw)}">${d.kw} <small>kW / เครื่อง</small></span></div><p>${esc(d.brand)} · ${esc(d.model)} · ${d.connectors} หัว</p><p>การรับประกัน: <span class="warranty-badge ${warrantyState(d)}">${warrantyLabel(d)}</span></p><small>${esc(d.id)}<br>พิกัด ${d.lat}, ${d.lon}</small>${d.damage?`<p style="color:var(--amber)">รายการชำรุด: ${esc(d.damage)}</p>`:''}<section class="pm-record"><h3>การบำรุงรักษาเชิงป้องกัน (PM)</h3><p><b>วันที่ดำเนินการ:</b> ${esc(d.pm||'ไม่ระบุข้อมูลวันที่ PM')}</p><p><b>รายละเอียดงาน:</b> ${esc(d.pmDetail||'ไม่ระบุรายละเอียดงาน PM')}</p></section><h3>ประวัติการเข้าดำเนินการซ่อมบำรุง</h3>${d.repairs.length?d.repairs.map(r=>`<div class="repair"><span class="repairdate">วันที่เข้าดำเนินการ: ${esc(r.date||'ไม่ระบุวันที่')}${r.dateInherited?' *':''}</span><b>รายละเอียดงาน: ${esc(r.item)}</b><div class="cost">${r.cost!=null?'ค่าใช้จ่าย: '+fmt(r.cost)+' บาท':'ไม่ระบุราคา'}</div><small>${esc('หมายเหตุ: '+(r.note||'ไม่ระบุ'))}</small><small>ประวัติการซ่อมแซม · แถว ${r.row}</small></div>`).join(''):'<p class="emptyrepair">ไม่พบประวัติการซ่อมบำรุงในทะเบียน</p>'}</article>`).join('')+'<small>* วันที่ใช้ร่วมกับแถวก่อนหน้าในกลุ่มเครื่องเดียวกัน เมื่อแถวรายการไม่ได้ระบุวันที่ใหม่</small>'}
function project(lat,lon){const s=256*2**zoom;return[(lon+180)/360*s,(1-Math.log(Math.tan(lat*Math.PI/180)+1/Math.cos(lat*Math.PI/180))/Math.PI)/2*s]}
function drawMap(){const w=$('#map').clientWidth,h=$('#map').clientHeight,ds=visible(),focus=sites.find(s=>s.id===selected)?.devices[0];const [cx,cy]=project(zoom>7&&focus?focus.lat:17.65,zoom>7&&focus?focus.lon:100),left=cx-w/2,top=cy-h/2;let tiles='';for(let x=Math.floor(left/256);x<=Math.floor((left+w)/256);x++)for(let y=Math.floor(top/256);y<=Math.floor((top+h)/256);y++)tiles+=`<img alt="" src="https://tile.openstreetmap.org/${zoom}/${x}/${y}.png" style="left:${x*256-left}px;top:${y*256-top}px" loading="lazy">`;$('#tiles').innerHTML=tiles;$('#markers').innerHTML=sites.filter(s=>s.devices.some(d=>ds.includes(d))).map(s=>{const d=s.devices[0],[x,y]=project(d.lat,d.lon),state=s.devices.every(d=>d.status==='ใช้งาน')?'online':'offline';return `<button class="marker ${state} ${s.id===selected?'selected':''}" data-site="${esc(s.id)}" aria-label="${esc(d.name)}" title="${esc(d.name)}" style="left:${x-left}px;top:${y-top}px;width:36px;height:36px">${s.devices.length}</button>`}).join('');$('#maptip').hidden=true;document.querySelectorAll('[data-site]').forEach(b=>b.onclick=()=>{selected=b.dataset.site;detail();drawMap();revealStation()})}
['center','power','status','warranty'].forEach(id=>$('#'+id).onchange=render);$('#search').oninput=render;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#plus').onclick=()=>{zoom=Math.min(15,zoom+1);drawMap()};$('#minus').onclick=()=>{zoom=Math.max(5,zoom-1);drawMap()};$('#export').onclick=()=>{const q=s=>{let v=String(s??'');if(typeof s==='string'&&/^[=+\-@\t\r]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"'};const rows=[['สถานี','Station No.','Charger ID','กำลัง kW','สถานะ','รายการซ่อม','ราคา','วันที่','หมายเหตุ'],...visible().flatMap(d=>(d.repairs.length?d.repairs:[{}]).map(r=>[d.name,d.site,d.id,d.kw,d.status,r.item,r.cost,r.date,r.note]))];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(q).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='PEA-VOLTA-stations-repairs.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};window.addEventListener('resize',drawMap);
function setDataset(ds){const oldOffice=$('#center').value;chargers=ds;sites=[...new Set(chargers.map(d=>d.site))].map(id=>({id,devices:chargers.filter(d=>d.site===id)}));$('#center').innerHTML='<option value="">ทุกหน่วยงาน</option>';[...new Set(chargers.map(d=>d.office).filter(Boolean))].sort().forEach(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;$('#center').append(o)});if([...$('#center').options].some(o=>o.value===oldOffice))$('#center').value=oldOffice;render();}


function openRepairs(devices){
 const records=devices.flatMap(d=>d.repairs.map(r=>({device:d,repair:r})));
 $('#repair-title').textContent=devices.length===1?'ประวัติการซ่อมบำรุง · '+devices[0].name:'ประวัติการซ่อมบำรุงตามตัวกรอง';
 $('#repair-content').innerHTML=`<p>${records.length} รายการ · เลือกรายการเพื่อแสดงรายละเอียด</p>`+records.map(({device:d,repair:r},i)=>`<button class="repair-list-entry" data-repair-index="${i}"><strong>${esc(d.name)}</strong><span>${esc(r.item)}</span><small>วันที่เข้าดำเนินการ: ${esc(r.date||'ไม่ระบุวันที่')} · ${r.cost!=null?fmt(r.cost)+' บาท':'ไม่ระบุค่าใช้จ่าย'}</small></button>`).join('')+(records.length?'':'<p class="emptyrepair">ไม่พบประวัติการซ่อมบำรุงตามตัวกรอง</p>');
 document.querySelectorAll('[data-repair-index]').forEach(b=>b.onclick=()=>{const {device:d,repair:r}=records[Number(b.dataset.repairIndex)];$('#repair-content').innerHTML=`<button id="repair-back">กลับสู่รายการซ่อมบำรุง</button><dl class="repair-fields"><dt>สถานี / เครื่องอัดประจุ</dt><dd>${esc(d.name)}</dd><dt>รหัสเครื่อง</dt><dd>${esc(d.id)}</dd><dt>หน่วยงานรับผิดชอบ</dt><dd>${esc(d.office)}</dd><dt>วันที่เข้าดำเนินการ</dt><dd>${esc(r.date||'ไม่ระบุวันที่')}${r.dateInherited?' (อ้างอิงวันที่ของรายการก่อนหน้าในกลุ่มเดียวกัน)':''}</dd><dt>รายละเอียดงาน / อะไหล่</dt><dd>${esc(r.item)}</dd><dt>ค่าใช้จ่าย</dt><dd>${r.cost!=null?fmt(r.cost)+' บาท':'ไม่ระบุค่าใช้จ่าย'}</dd><dt>หมายเหตุ</dt><dd>${esc(r.note||'ไม่ระบุหมายเหตุ')}</dd></dl>`;$('#repair-back').onclick=()=>openRepairs(devices)});
 if(!$('#repair-dialog').open)$('#repair-dialog').showModal();
}

function revealStation(){if(window.matchMedia("(max-width:760px)").matches)document.querySelector(".geo-grid aside").scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});}
